use warehouse chipmunk_wh;
use role training_role;
use database chipmunk_db;
CREATE schema SMARTDESK;

SELECT *
FROM ACCOUNTS;

SELECT *
FROM FORECASTS;

SELECT *
FROM SALES;

SELECT *
FROM ACCOUNTS;

--- 1. Análisis de Ventas y Beneficio por Categoría de Producto para Adabs Entertainment en 2020

SELECT 
    CATEGORY AS CATEGORIA_PRODUCTO,
    SUM(MAINTENANCE) AS TOTAL_MANTENIMIENTO,
    SUM(PRODUCT) AS TOTAL_PRODUCTO,
    SUM(PARTS) AS TOTAL_PARTES,
    SUM(SUPPORT) AS TOTAL_SOPORTE,
    SUM(TOTAL) AS VENTAS_TOTALES,
    SUM(UNITS_SOLD) AS TOTAL_UNIDADES_VENDIDAS,
    SUM(PROFIT) AS BENEFICIO_TOTAL
FROM SALES
WHERE ACCOUNT = 'Adabs Entertainment' AND YEAR = 2020
GROUP BY CATEGORY;

--- 2. Comparación de Ventas, Unidades Vendidas y Beneficio entre Industrias en las Regiones APAC y EMEA

SELECT 
    A.C6 AS INDUSTRY,
    A.C5 AS COUNTRY, 
    A.C7 AS REGION,
    SUM(S.PRODUCT) AS TOTAL_PRODUCTO, 
    SUM(S.UNITS_SOLD) AS TOTAL_UNIDADES_VENDIDAS,
    SUM(S.PROFIT) AS BENEFICIO_TOTAL, 
    AVG(S.PROFIT) AS BENEFICIO_PROMEDIO, 
FROM SALES AS S
INNER JOIN ACCOUNTS AS A
ON S.ACCOUNT = A.C1
WHERE REGION = 'APAC' OR REGION = 'EMEA'
GROUP BY INDUSTRY, COUNTRY, REGION
ORDER BY BENEFICIO_PROMEDIO DESC;

--3.Clasificación de Beneficio por Tipo de Empresa

--SUBCONSULTA
SELECT DISTINCT ACCOUNT
FROM FORECASTS
WHERE FORECAST > 500000 AND YEAR= 2022;

-- CONSULTA PRINCIPLA
SELECT A.C6 AS INDUSTRY, SUM(S.PROFIT) AS BENEFICIO_TOTAL,
CASE WHEN BENEFICIO_TOTAL > 1000000 THEN 'Alto'
     ELSE 'Normal'
END AS "CATEGORIA_DE_BENEFICIO"
FROM SALES AS S
INNER JOIN ACCOUNTS AS A
ON S.ACCOUNT = A.C1
WHERE S.ACCOUNT IN (SELECT DISTINCT ACCOUNT
FROM FORECASTS
WHERE FORECAST > 500000 AND YEAR= 2022)
GROUP BY INDUSTRY
ORDER BY BENEFICIO_TOTAL DESC;

--4 Comparación de Beneficios para Diferentes Años

SELECT 
    COALESCE(S.CATEGORY, F.CATEGORY) AS CATEGORIAS, 
    SUM(CASE WHEN S.QUARTER = '2020 Q1' THEN S.PROFIT ELSE 0 END) AS BENEFICIO_TOTAL_Q1_2020,
    SUM(CASE WHEN S.QUARTER = '2021 Q3' THEN S.PROFIT ELSE 0 END) AS BENEFICIO_TOTAL_Q3_2021,
    SUM(F.FORECAST) AS FORECAST_TOTAL,
    MAX(F.OPPORTUNITY_AGE) AS OLD_OPPORTUNITY, 
    MIN(F.OPPORTUNITY_AGE) AS YOUNG_OPPORTUNITY
FROM SALES AS S
LEFT JOIN FORECASTS AS F
ON S.CATEGORY = F.CATEGORY
WHERE S.QUARTER IN ('2020 Q1', '2021 Q3')
GROUP BY COALESCE(S.CATEGORY, F.CATEGORY)
ORDER BY FORECAST_TOTAL DESC;

--5. Cálculo del Beneficio Acumulado por Trimestre y por Industria

SELECT DISTINCT 
       A.C6 AS INDUSTRY, 
       S.QUARTER,
       SUM(S.PROFIT) OVER (PARTITION BY A.C6 ORDER BY S.QUARTER) AS Beneficio_Acumulado,
       SUM(F.FORECAST) OVER (PARTITION BY A.C6 ORDER BY S.QUARTER) AS Pronostico_Acumulado,
       SUM(S.PROFIT) OVER (PARTITION BY A.C6) AS Beneficio_Acumulado_total,
       ROUND(AVG(S.PROFIT) OVER (PARTITION BY A.C6), 2) AS Beneficio_Promedio_total
FROM SALES AS S
INNER JOIN ACCOUNTS AS A
    ON S.ACCOUNT = A.C1
INNER JOIN FORECASTS AS F 
    ON S.ACCOUNT = F.ACCOUNT 
   AND S.CATEGORY = F.CATEGORY
QUALIFY ROW_NUMBER() OVER (PARTITION BY A.C6, S.QUARTER ORDER BY S.QUARTER) = 1
ORDER BY Beneficio_Acumulado_total desc, INDUSTRY, S.QUARTER;

---Caso Práctico: Análisis Libre

--- Descubrir que paises e industrias son mas rentables 
CREATE OR REPLACE VIEW CountryIndustryProfit AS
SELECT 
       A.C5 AS COUNTRY,
       A.C6 AS INDUSTRY, 
       SUM(S.PROFIT) AS PROFIT_TOTAL
FROM ACCOUNTS AS A
INNER JOIN SALES AS S
ON A.C1 = S.ACCOUNT
GROUP BY A.C5, A.C6
ORDER BY PROFIT_TOTAL DESC;

----desempeño por categoría y tipo de venta dentro de estas industrias en Estados Unidos,

CREATE OR REPLACE VIEW IndustryCategoryProfit_US AS
SELECT 
       A.C6 AS INDUSTRY, 
       S.CATEGORY AS CATEGORIA,
       COALESCE(SUM(S.MAINTENANCE), 0) AS MANTENIMIENTO,
       COALESCE(SUM(S.PARTS), 0) AS PARTES,
       COALESCE(SUM(S.SUPPORT), 0) AS SOPORTE,
       COALESCE(SUM(S.PRODUCT), 0) AS PRODUCTO,
       COALESCE(SUM(S.UNITS_SOLD), 0) AS UNIDADES_VENDIDAS,
       COALESCE(SUM(S.PROFIT), 0) AS PROFIT_TOTAL
FROM ACCOUNTS AS A
INNER JOIN SALES AS S
ON A.C1 = S.ACCOUNT
WHERE A.C5 = 'United States' 
  AND A.C6 IN ('Finance', 'Retail', 'Law', 'Consulting', 'Entertainment and Media')
GROUP BY A.C6, S.CATEGORY
ORDER BY PROFIT_TOTAL DESC;


---Margen de ganancia por unidad vendida y volumen de ventas por industria y categoría 

SELECT 
       A.C6 AS INDUSTRY, 
       S.CATEGORY AS CATEGORIA,
       COALESCE(SUM(S.UNITS_SOLD), 0) AS UNIDADES_VENDIDAS,
       COALESCE(SUM(S.PROFIT), 0) AS PROFIT_TOTAL,
       CASE 
           WHEN COALESCE(SUM(S.UNITS_SOLD), 0) > 10000 THEN 'ALTO VOLUMEN'
           ELSE 'BAJO VOLUMEN'
       END AS VOLUMEN,
       ROUND(COALESCE(SUM(S.PROFIT), 0) / NULLIF(COALESCE(SUM(S.UNITS_SOLD), 0), 0), 2) AS MARGEN_POR_UNIDAD
FROM ACCOUNTS AS A
INNER JOIN SALES AS S
ON A.C1 = S.ACCOUNT
WHERE A.C5 = 'United States' 
  AND A.C6 IN ('Finance', 'Retail', 'Law', 'Consulting', 'Entertainment and Media')
  AND S.CATEGORY IN ('Break room', 'Electronics', 'Desks', 'Chairs')
GROUP BY A.C6, S.CATEGORY
ORDER BY MARGEN_POR_UNIDAD DESC;

